# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-Simple
version:      1.24
version_from: lib/DBIx/Simple.pm
installdirs:  site
requires:
    Data::Swap:                    0.02
    DBI:                           1.21

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
